### ISSUE TITLE
Pass arguments to factory.create thru acquire

### ISSUE THREAD

**Issue by smelukov** [coopernurse/node-pool#101]
For example: I want to create pool of `JsonRPC` requests.
And it would be great, if I would pass arguments to `factory.create` thru `acquire`

```javascript
var JsonRPC = require('jsonrpc'),
	requestsPool = PoolModule.Pool({
		name: 'jsonrpc',
		create: function(options, callback) {
			callback(null, new JsonRPC(options.method, options.params));
		}
	});

pool.acquire({method: 'getUser', params: {id: 777}}, function(err, client) {...});
```

**Comment by sandfox** [comment]
A resource pool is designed to offer a pool of identical and re-usable resources. If you pass in configuration at `acquire` time then that resource would only be re-usable if someone else calling acquire has exactly the same configuration. If you are passing in the same configuration every time then you could just as easily pass it in when defining the `factory.create` method.

I'm just guessing but judging by the code above what you'd really need is another layer such that `jsonrpc` itself has access to resource pool of http/tcp connections (which don't know or care about methods/params etc) and re-uses them as it needs to, but the end person using `jsonrpc` has no idea about it.
