### ISSUE TITLE
hangs on exit because of setTimeout

### ISSUE THREAD

**Issue by vitaly-t** [coopernurse/node-pool#102]
Since the pool relies on a time-out interval, it uses `setTimeout` to see when the pool is to expire.

But the way it does so is incorrect, preventing the process from exiting until the pool has expired.

What it should do instead, use periodic `setTimeout` with a small pause, like 1-2 seconds, each time to check against the actual time-out, and if it hasn't been reached yet, call another `setTimeout`, and so on.

If you do it this way, then you do not need to manually destroy the pool at the point where your application is supposed to exit, because you would wait only up to the corresponding 1-2 seconds, at most.

**Comment by vitaly-t** [comment]
Please ignore this.

**Comment by jeromew** [comment]
it seems that your problem is adressed by

https://github.com/coopernurse/node-pool#step-3---drain-pool-during-shutdown-optional

**Comment by vitaly-t** [comment]
That just releases all pools manually. The approach that I suggested was to make sure that you do not have to terminate the library manually, i.e. to be able to exit automatically when the process finishes.

It is a big deal for this type of library, because otherwise all the libraries that use it are unable to exit the process automatically, they all have to make a manual call for that, which isn't very nice, but more importantly, it is avoidable, as I suggested earlier.

**Comment by jeromew** [comment]
I am not too familiar with the `unref` solution. The doc on https://nodejs.org/api/timers.html#timers_unref states

>In the case of setTimeout when you unref you create a separate timer that will wakeup the event loop, >creating too many of these may adversely effect event loop performance -- use wisely.

In the case of generic-pool on a moderately hit server, the connections come and go, many timers are created. I don't know how bad the warning from the documentation is.

**Comment by sandfox** [comment]
Whilst I could be wrong, this seems like a fairy theoretical problem that only comes into effect in current scenarios

1. the resources you are managing are themselves weakly referenced and therefore don't stop the application from quitting. (which isn't the case for most I/O handles, TCP connections, database drivers, etc)
2. your pool min size is set to zero. If it's not then whatever resources you are managing are probably going to keep the event loop spinning anyway.

I'm sure those both of those situations do exist but in those circumstances it's probably not too hard to just manually call `drain` + `destroyAllNow` if a quick shutdown really is required. (e.g by attaching an event handler to a `process` signal).

This is pretty low priority so I'm probably not going to work on it, but I'd be open for maybe accepting a pull request if the code was simple enough.
