### ISSUE TITLE
availableObjects.length > factory.max 

### ISSUE THREAD

**Issue by devzer01** [coopernurse/node-pool#103]
i have a reproducible case where generic-pool creates more connections than whats specified at factory.max

steps to reproduce

- create a pool with with minimum 1 connection and set the idletimeout to be higher than dbserver idletimeout (example dbpool-idletimeout 5 seconds, server idletimeout 2 seconds)

following is the code used to create the pool

```
var pool = createPool();

function createPool() {
    return imports.genericPool.Pool({
        name     : config.database.adapter,
        create   : function(callback) {
            var c = new imports.mariasql();
            c.connect({
                host: config.database.host,
                user: config.database.user,
                password: config.database.password,
                db: config.database.database
            });
            c.on('connect', function () {
                logger.debug("Connecting to database");
                callback(null, c);
            }).on('error', function (err) {
                logger.debug("Connect error:" + err + config.database.host);
                callback(err, null);
            }).on('close', function (hadError) {
                logger.debug("Closing connection to database, hadError:" + hadError);
            }).on('end', function () {
                logger.debug("client on end");
            }).on('ready', function () {
                logger.debug("connection ready");
            });
        },
        destroy  : function(client) {
            logger.debug("destory pool");
            client.end();
        },
        max      : 5,
        min      : 1,
        idleTimeoutMillis : 5000,
        log : function (message, level) {
            logger.debug("DBPOOL LOG " + level + " " + message);
        },
        returnToHead: true
    });
}
```

there is no need to execute any queries, just create a pool with above code and either (kill the connection manually from the db or lower the timeout in db than whats specified in the pool. everytime a connection is killed pool will start +1 connections.

**Comment by devzer01** [comment]
issue resolved in the submitted PR. 

pretty much if count becomes negative it creates more connections than MAX.

**Comment by sandfox** [comment]
@devzer01 thanks for discovering this. I'l try and have a look at this sometimes before next week and merge it. From a quick look it looks good though.

(one day I'll ram in a proper state machine in there somewhere!)

**Comment by devzer01** [comment]
@sandfox thanks pushed another commit :)

**Comment by sandfox** [comment]
@devzer01 Thanks a bundle, thats merged and published to NPM!
