### ISSUE TITLE
sync destroy when IdleTimeoutMillis = 0

### ISSUE THREAD

**Issue by jeromew** [coopernurse/node-pool#107]
Hello,

I was wondering if it would make sense to have a specific case when IdleTimeoutMillis = 0 that would destroy the connection when released.

I understand that this is a corner case of generic-pool since the goal of generic pool is to maintain a pool of active connections.

I am a happy user of generic-pool and use it to maintain pools over several backends (postgres, redis, sqlite). Now I would like to use the same wrapper to create connections to a temporary sqlite :memory: database but I do not want it to be shared with another subsequent acquisition because there would be data lying around in the database.

having a way to always destroy released connections immediatly would also be a nice way to put any system in a "no pooling" mode.

**Comment by sandfox** [comment]
While not quite an answer to your question, with the current (v2) pool, it's possible to do the following to destroy items when returning them

```
pool.release(resource)
pool.destroy(resource)
```

(see #80 for why you need to call `release` before calling `destroy`)

Rather than overloading the meaning of `IdleTimeoutMillis` I'd rather have an explicit method of config setting for this kind of behaviour.

**Comment by jeromew** [comment]
Thanks for your answer.
I agree that overloading the meaning is not the best idea. I'll see if I can use the release/destroy sequence just  for the sqlite/memory scenario in my wrapper.

**Comment by sandfox** [comment]
yeah, when we can break BC (next major version), you'll just need to call `pool.destroy` (or an equivalent function) and that will invoke all the necessary internals for you. 

Having read the apache commons pool, they seem to do it in a similar way 
https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/GenericObjectPool.html#invalidateObject-T-
