### ISSUE TITLE
Make Pool a class, put methods on prototype

### ISSUE THREAD

**Issue by felixfbecker** [coopernurse/node-pool#111]
Currently, `Pool` is just a factory function that creates an object literal an puts a bunch of function properties on it. This is not the most memory-efficient way and makes it impossible to promisify this library with something like Bluebird's `promisifyAll`, because `Pool` doesn't have a prototype.

I propose that all methods like `aquire`, `release` get put on the prototype of Pool, and inside of Pool a line gets added `if (!(this instanceof Pool)) return new Pool(options)` to still allow the use without `new` (express and many others do it this way). No bc breaks.

If you are ok with this, I would submit a PR.

**Comment by sandfox** [comment]
Hi @felixfbecker - in principle I'm totally for this and have been toying with doing this, but my javascript-foo isn't sufficiently strong to be 100% sure that it won't cause any problems for anyone downstream, that said I can't think of any obvious problems. So yes, please submit a PR :+1: 

If you have the time and inclination feel free to something similar for priority queue as well.

**Comment by felixfbecker** [comment]
@sandfox :+1: 
All the variables inside the function will need to become properties. Which of these should become private (prefixed with an underscore) and which of them public?
```js
var idleTimeoutMillis = factory.idleTimeoutMillis || 30000,
      reapInterval = factory.reapIntervalMillis || 1000,
      refreshIdle = ('refreshIdle' in factory) ? factory.refreshIdle : true,
      availableObjects = [],
      inUseObjects = [],
      waitingClients = new PriorityQueue(factory.priorityRange || 1),
      count = 0,
      removeIdleScheduled = false,
      removeIdleTimer = null,
      draining = false,
      returnToHead = factory.returnToHead || false,
      log ...

**Comment by felixfbecker** [comment]
I could also implement it as an ES6 class, but then the Node requirement would have to be raised to 4.0.0. Think about it, 0.2 is _really_ old :D

**Comment by sandfox** [comment]
re: ES6

At least for time being I'd like to keep this working for old pre v4 versions of node as I know this library is quite widely used and there are still many instances of where upgrading from 0.8/0.10 isn't yet on the cards. 

I agree as ES6 class would be nice and  `var self = this` is a bit of pain but I'd prefer to keep such a breaking change for v3 where we can really go to town and use a bunch of other ES6 features as well to clean up the internals.

sorry to be a pain

**Comment by sandfox** [comment]
re: properties

Considering how it currently works I feel they should all be internal as right now they are all inaccessible directly, and a few have `getters`. I'd rather keep the internals the hidden away so changing them in the future is easy.
