### ISSUE TITLE
Switch from expresso to mocha

### ISSUE THREAD

**Issue by felixfbecker** [coopernurse/node-pool#112]
expresso is no longer maintained and users are recommended to switch to mocha, see https://github.com/visionmedia/expresso. It is causing issues for me because expresso has a pre-install hook that uses make, which is not available on Windows.

mocha supports an export style which is compatible with the expresso style, or I could rewrite the tests to use mocha BDD style. Would PR be welcome?

**Comment by sandfox** [comment]
There's already an existing issue for this #75 but I haven't had much time to really do anything about , my preference is for something simple like tap/tape but if it's reasonably easy and quick to just switch over to mocha with exports style and it makes things work for you then thats cool with me. 
PR's welcome :-)
