### ISSUE TITLE
if min and max are both 1, the pool silently set the min to 0

### ISSUE THREAD

**Issue by molipet** [coopernurse/node-pool#119]
As stated in the documentation:
> min: minimum number of resources to keep in pool at any given time
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          if this is set > max, the pool will silently set the min to factory.max - 1

It looks to me that not only on `min > max` but also on `min == max`, the `factory.max - 1` is applied.
Resulting that `min` will be disregarded in case of `max=1` and `min=1`.

**Comment by sandfox** [comment]
Ah yes :-) this has already been flagged in #79 and fixed in the v3 branch but never got round to fixing the docs for the current version (v2).

**Comment by molipet** [comment]
Documentation is fixed in #120.

**Comment by sandfox** [comment]
thanks for this @molipet :100:
