### ISSUE TITLE
Add note about AsyncValidation - zalgo

### ISSUE THREAD

**Issue by sandfox** [coopernurse/node-pool#131]
Need to put a note in the README about how any async validation function should always call the callback on another spin of the event loop e.g `setImmediate` and not the inside the same was it was invoked.

**Comment by felipou** [comment]
This will be fixed by this pull request I just created: https://github.com/coopernurse/node-pool/pull/142

**Comment by sandfox** [comment]
this is now no longer a possible problem due to the promise interface in v3
