### ISSUE TITLE
Version 2.4.1 breaks refreshIdle functionality

### ISSUE THREAD

**Issue by ijaooo** [coopernurse/node-pool#137]
Commit 2cee31a56fb7f20b78a6a1ba8149954def5d2829 broke the original refreshIdle functionality: if refreshIdle is true and min pool size is set, connections in the pool will never timeout.

Only workaround is to set min to 0, but this would defeat the purpose of having a pool.

Can we have the commit rolled back by changing  
_this._factory.refreshIdle **&&** (this._count..._ 
in line 214 back to 
_this._factory.refreshIdle **||** (this._count..._

**Comment by sandfox** [comment]
Thanks for reporting this, I'll try and get round to looking at this soon, in the meantime something to consider that reverting that commit will re-introduce the bug that commit is removing which isn't helpful.

**Comment by ijaooo** [comment]
Agree. But this commit directly introduces a new bug which renders existing functionality unusable - we have no way to force the refresh of idle connections.

**Comment by hyss777** [comment]
I've come up with similar bug with version2.4.2 also.
The package fail to keep the connection in the latest version.

My solution for the time is add a error listener in node-mysql's connection object.
as the below code goes，
However, this should actually be a bug. 

`E.Pool=new Pool.Pool
  name:'mysql'
  create:(callback)->
    c=Mysql.createConnection(some_config)
    c.on 'error', (e)->
      if e.code=='PROTOCOL_CONNECTION_LOST'
        E.Pool.destroy c
      else
        throw e
    callback(null,c)
    .....
`

**Comment by sandfox** [comment]
ok, finally got to the bottom of this. It would seem the intent behind the `refreshIdle` flag was little unclear / misunderstood by me and the committer. I'm going to revert `2cee31a` and probably add a litte note explaining the desired behaviour and release this on the `2.4` branch. 
v3 has the option to specify whether idleTimeouts affect should affect resources below the "min" count.

**Comment by sandfox** [comment]
fixed in version 2.4.6
