### ISSUE TITLE
Process hangs with refreshIdle: false

### ISSUE THREAD

**Issue by olalonde** [coopernurse/node-pool#148]
`refreshIdle: false` should prevent the remove timeout from being called, but it doesn't: https://github.com/coopernurse/node-pool/blob/master/lib/generic-pool.js#L243

**Comment by sandfox** [comment]
The documentation around refreshIdle (and it's name) is a little unclear. What it really means is "should I timeout resources which are part of the min pool size"
It doesn't turn off/on the general timeout behaviour - that is controlled by `reapInterval` and `idleTimeoutMillis`

Feel free to re-open this if you still something is broken.
