### ISSUE TITLE
this._factory.validate is not a function

### ISSUE THREAD

**Issue by pasupulaphani** [coopernurse/node-pool#162]
```
ERROR: this._factory.validate is not a function

FULL BACKTRACE:
/app/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:304
/app/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:392
/app/node_modules/knex/lib/client.js:281
/app/node_modules/bluebird/js/release/debuggability.js:299
/app/node_modules/bluebird/js/release/promise.js:481
/app/node_modules/bluebird/js/release/promise.js:77
/app/node_modules/knex/lib/client.js:272
/app/node_modules/knex/lib/runner.js:200
/app/node_modules/bluebird/js/release/debuggability.js:299
/app/node_modules/bluebird/js/release/promise.js:481
/app/node_modules/bluebird/js/release/promise.js:77
/app/node_modules/knex/lib/runner.js:198
/app/node_modules/bluebird/js/release/util.js:16
/app/node_modules/bluebird/js/release/method.js:39
/app/node_modules/knex/lib/runner.js:197
/app/node_modules/knex/lib/runner.js:47
/app/node_modules/knex/lib/interface.js:35
/app/node_modules/bluebird/js/release/util.js:16
/app/node_modules/bluebird/js/release/thenables.js:63
/app/node_modules/bluebird/js/release/thenables.js:28
/app/node_modules/bluebird/js/release/generators.js:151
/app/node_modules/bluebird/js/release/generators.js:99
/app/node_modules/bluebird/js/release/generators.js:201
```

Has anyone experienced this?

**Comment by pasupulaphani** [comment]
Please close this if it is irrelevant.

ref: https://github.com/tgriesser/knex/issues/1787

**Comment by sandfox** [comment]
This is most likely down to whatever code is using pool or knex incorrectly passing in some options to the pool (and/or knex).

**Comment by pasupulaphani** [comment]
@sandfox , we debugged a lot and found that the reference is being lost somewhere. But Knex is passing the validate function correctly. Unfortunately we cannot reproduce the error locally.

If you have any vague thoughts with your experience would be useful. This happens seldomly when there is a bulk of connection requests made.

**Comment by sandfox** [comment]
As far as I can tell `pool._factory.validate` is only ever set inside the pool constructor, so there is no place for the pool itself to "unset" that variable. If it is being unset or overwritten it is most likely some external code doing so.
Seeing the error message `this._factory.validate is not a function` It would seem that something is over-writing the property with a value that isn't a function. 
Without some example code I can't debug this, but you might be able to find out what is changing the value by using [ES6 proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)  to catch any access of the property, or if in an ES5 environment, hack in some getters/setters
