### ISSUE TITLE
Feature request: .use method?

### ISSUE THREAD

**Issue by olalonde** [coopernurse/node-pool#167]
Would be nice to have a method that automatically acquires and releases a resource, e.g.:

```javascript
pool.use(resource => {
  return resource.doSomething().then(console.log)
})
```

It would be implemented something like this (haven't tested):

```javascript
  pool.use = (fn) => {
    pool.acquire().then(resource => {
      fn(resource)
        .then((result) => {
          pool.release(resource)
          return result
        }, (err) => {
          pool.release(resource)
          throw err
        })
    })
  }
```

Thoughts?

**Comment by sandfox** [comment]
At a first glance from my phone this seems a little bit like the promisey version of https://github.com/sandfox/generic-pool-decorator ?

**Comment by olalonde** [comment]
Yep, looks like :) Though I really this should be part of node-pool since it's such a common usage pattern.

**Comment by olalonde** [comment]
```javascript
  pool.use = (fn) => {
    let resource
    return pool.acquire()
      .then(r => {
        resource = r
        return resource
      })
      .then(fn)
      .then((result) => {
        pool.release(resource)
        return result
      }, (err) => {
        pool.release(resource)
        throw err
      })
  }
```

**Comment by sandfox** [comment]
I think in general I'm down with this, I probably won't get much time to do anything about this till the weekend though.

**Comment by malthe** [comment]
Isn't the general case here that `fn` would return a promise itself?

**Comment by binki** [comment]
@malthe Yeah. The point is that it would return a `Promise` which would complete (reject or resolve) whenever it's done using the resource. Then it doesn't need to remember to release the resource because everything is scope-driven—especially when used with `async`/`await`.

**Comment by binki** [comment]
@malthe Are you confused about something? The example code here works both when `fn` returns a `Promise` and also when `fn` returns something other than a `Promise`. See docs for how `.then()` works.

**Comment by malthe** [comment]
The [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/427e697c4229f096f262b59b3067283769e666ba/types/generic-pool/index.d.ts#L26) has it like this: `use<U>(cb: (resource: T) => U): PromiseLike<U>`.

But I would have expected: `use<U>(cb: (resource: T) => PromiseLike<U>): PromiseLike<U>`.

**Comment by binki** [comment]
@malthe Looks like the type definitions are coming from the DefinitelyTyped project, not this project. The correct place to report issues about your typings is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues). Please see also [DefinitelyTyped’s contribution guide](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute).
