### ISSUE TITLE
Infinite loop if error is thrown inside factory create method.

### ISSUE THREAD

**Issue by amokrushin** [coopernurse/node-pool#194]
Example code:
```js
const genericPool = require('generic-pool');

const pool = genericPool.createPool(
    {
        create() {
            return new Promise(() => {
                throw new Error();
            });
        },
        destroy() {
            return Promise.resolve();
        },
    },
);

pool.acquire();
```

Process wil take all available memory until heap out of memory exception.

It seems that error must be caught on factoryPromise and handled properly:
https://github.com/coopernurse/node-pool/blob/33ea5efe0b486a005a682dda2973d578da9ea43a/lib/Pool.js#L279

**Comment by amokrushin** [comment]
Closed. I have read the readme better.
Anyway I don't think that silently discarding the error by default is a good solution. By default error must be thrown as "Unhandled 'error' event" if error handler was not set.

**Comment by sandfox** [comment]
Becuase this module runs in asynchronous way (i.e work is happens across different spins of the event loop), it's not possible to `throw` errors and expect them to be caught in userland.

That said, maybe I need to make it clearer in the README about error handling.

**Comment by amokrushin** [comment]
> it's not possible to throw errors

It is not so, for example
```js
new Promise(() => {
  throw Error('foo')
}).catch(err => {
  console.log(err.message);
})
```
will print "foo" as expected

Initially I mean a different issue, that generic-pool does not handle factory.create rejections properly, and code like
```js
const genericPool = require('generic-pool')
const pool = genericPool.createPool(
  {
    create: () => Promise.reject(),
    destroy: () => Promise.resolve()
  }
)
pool.acquire()
```
takes >1G RAM in a few seconds

Then I have read readme better and found that
```js
pool.on('factoryCreateError', (err) => {
  throw err
})
```
can eliminate infinity loop

**Comment by alolis** [comment]
Why is this issue closed?
