### ISSUE TITLE
It does not respect when maxWaitingClients is set to 0

### ISSUE THREAD

**Issue by anupbaldawa** [coopernurse/node-pool#234]
I want my code to fail when I set `maxWaitingClients` to `0`.

I looked into the code and it seems that if I pass in `0`, then it is ignored as the `if condition` is false.

https://github.com/coopernurse/node-pool/blob/master/lib/PoolOptions.js#L75

**Comment by sandfox** [comment]
good catch, as I wrote that code over 2 years ago I'm not exactly sure what the intention was but I strongly expect that I just wasn't paying attention to that case. I'll gladly except a PR that does something like:

```js
    if (opts.maxWaitingClients != undefined) {
      // @ts-ignore
      this.maxWaitingClients = parseInt(opts.maxWaitingClients, 10);
    }
```

**Comment by anup-honey** [comment]
Here is the PR:
https://github.com/coopernurse/node-pool/pull/235

Thanks
Anup

**Comment by anup-honey** [comment]
I have created another PR with test cases.
https://github.com/coopernurse/node-pool/pull/236
