### ISSUE TITLE
【pool.use】The document description does not conform to the actual logic.

### ISSUE THREAD

**Issue by LincWong** [coopernurse/node-pool#257]
### The document said:
![image](https://user-images.githubusercontent.com/1209664/54904362-47ddb680-4f19-11e9-8f64-4e6bf1646006.png)

### But the actual code is:
![image](https://user-images.githubusercontent.com/1209664/54904416-722f7400-4f19-11e9-9968-045ae7905479.png)

**Comment by sandfox** [comment]
Excellent spot! I think this is probably a mistake made when writing the method. I'll have a another look later and double check it, and then I'll probably correct the code to match the documentation.
