### ISSUE TITLE
PromiseLike makes the API really awkward

### ISSUE THREAD

**Issue by t3hmrman** [coopernurse/node-pool#259]
As a new user I found that I had to write code like the following due to the use of `PromiseLike` (which only [has one method, `.then(onSuccess, onRejection)`](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L1366)):

```typescript
    public cleanup(): Promise<DoneIndicator> {
        return new Promise((resolve, reject) => {
            this.pool.drain()
                .then(
                    () => this.pool.clear(), 
                    err => { throw err; },
                )
                .then(
                    () => this.getDoneIndicator(),
                    err => { throw err; },
                )
                .then(resolve);
        });
    }
```

The compiler rightfully complains about trying to use `.catch` on `PromiseLike`s, and that means that you need to use the slightly more awkward (in my opinion) second argument, and you can't just `reject` from there because the return type becomes separate (you'd have `Promise<resource | void>` instead of `Promise<resource>` since `reject` can't return the thing you wanted to do if everything succeeded).

This is less than ideal -- am I using this library and it's `@types` declarations correctly? Maybe the `@types` declaration should be changed to use `Promise` if that's what you all are actually using in `v3`? (If v3 is keeping ES5 compatibility then I totally understand)

**Comment by t3hmrman** [comment]
I see that I missed the `Promise` option which lets you change your promise implementation -- maybe this ticket should be about updating `@types/generic-pool` take that into account?

**Comment by sandfox** [comment]
I think this is a situation where the type-defs could probably be improved as `drain` returns an actual `Promise`.

**Comment by t3hmrman** [comment]
Is this as easy as it would seem? Would a well placed [PR to @types/generic-pool's `index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/generic-pool/index.d.ts) be good enough?

I imagine this might actually break people (@ compile time, hopefully), though, as the contracts of `Promise` and `PromiseLike` are so different

**Comment by sandfox** [comment]
I am not a typescript expert, but could the TS definitions be added directly to this repo?

**Comment by t3hmrman** [comment]
Yep, they could — I’ll make a PR

**Comment by radarfox** [comment]
If you do it like this, everything should work fine:

```
    return new Promise((resolve) => resolve(
      this.pool.drain()
      .then(() => this.pool.clear())
      .then(() => this.getDoneIndicator())
    ));
```

**Comment by t3hmrman** [comment]
Hey @radarfox the problem is that code does not handle failures of `pool.drain`. Also, this is specifically a typescript problem -- if you're not using Typescript you can just use `pool.drain` (and any of the other `Promise` producing functions) normally:

```javascript
this.pool.drain()
  .then(whatever)
  .catch(yourErrorHandlingCode)
```

The functions actually *return* `Promise`s, but the typescript type declaration files say that they return a `PromiseLike` which is a similar *but different* thing. The `PromiseLike` does *not* have a `.catch`, but expects you to call `.then` with two functions (ok and error cases).

From what I can tell, your wrapping of `this.pool.drain()` in a resolve doesn't actually do anything because:

1. You're not handling the `pool.drain` failure case with `.catch` (which *can* be used, again because `pool.drain` does return a `Promise`)
2. An instantly resolving promise (which resolves to a promise) doesn't do anything (you might as well use `Promise.resolve(...)`)

Unless I'm fundamentally misunderstanding

**Comment by radarfox** [comment]
You should probably dig a bit deeper into Promise API to understand everything.

> The functions actually return Promises, but the typescript type declaration files say that they return a PromiseLike which is a similar but different thing. The PromiseLike does not have a .catch, but expects you to call .then with two functions (ok and error cases).

My code returns `Promise` which has the `catch` method defined. If doesn't, you probably somehow broke native `Promise` implementation in `window.Promise`.

> You're not handling the pool.drain failure case with .catch (which can be used, again because pool.drain does return a Promise)

If you dont specify the second parameter of `Promise.then`, the error is passed on the upper level, just like with `trycatch`. You can catch all errors just by calling `cleanup().catch((e) => {...})`. It's a good practice to only catch on higher levels than in each method.

> An instantly resolving promise (which resolves to a promise) doesn't do anything (you might as well use Promise.resolve(...))

You are wrong, they are different. My code will ALWAYS return a Promise. Using `Promise.resolve` can result into thrown exception which will not be available at `cleanup().catch((e) => {...})`.

**Comment by t3hmrman** [comment]
> My code returns Promise which has the catch method defined. If doesn't, you probably somehow broke native Promise implementation in window.Promise.

`pool.drain` already does this, it returns a `Promise` already, there is no point in wrapping it in a new one...

> If you dont specify the second parameter of Promise.then, the error is passed on the upper level, just like with trycatch. You can catch all errors just by calling cleanup().catch((e) => {...}). It's a good practice to only catch on higher levels than in each method.

I was referring to the interface of `PromiseLike` -- it's not the same as `Promise`, which is the point. `pool.drain` is declared as a `PromiseLike` which has no such guarantee.

> You You are wrong, they are different. My code will ALWAYS return a Promise. Using Promise.resolve can result into thrown exception which will not be available at cleanup().catch((e) => {...}).

Nope, my point was that the code you wrote:

```javascript
    return new Promise((resolve) => resolve(
      this.pool.drain()
      .then(() => this.pool.clear())
      .then(() => this.getDoneIndicator())
    ));
```

Does *not* benefit from this feature, because `this.pool.drain` *already* returns a promise (which is what you `resolve` to), so it could be reduced to this:

```javascript
return Promise.resolve(this.pool.drain().then(...).then(...));
```
Unless you're talking about catching errors inside `drain` itself, which is essentially [one line outside of other internal `Promise` driven calls](https://github.com/coopernurse/node-pool/blob/a9fedbe83d11b7590e06fb54a05c8435824ba3f7/lib/Pool.js#L570), why would I not just call `this.pool.drain` directly?
