### ISSUE TITLE
Share pool between servers in a cluster

### ISSUE THREAD

**Issue by lroal** [coopernurse/node-pool#286]
Is there anyway to share the pool between multiple nodejs processes running in the same cluster ?
Something like this (not sure if this works, it is old): https://www.npmjs.com/package/node-pool-cluster

**Comment by Kikobeats** [comment]
do a `module.exports` of your pool, then It can be used by other file I guess?

**Comment by lroal** [comment]
That is not going to solve it.
I want to share the pool between all spawned child processes. Typically we create a node process for each CPU. 
Consider this a feature request if it is does not exist.

**Comment by lroal** [comment]
Pgbouncer typically solves this. But it would be great of  node-pool had this built-in.
