### ISSUE TITLE
Add destroy timeout to prevent pool.clear from hanging when destroy promise never resolves

### ISSUE THREAD

**Issue by cressie176** [coopernurse/node-pool#288]
Hello, and thank you for this library. We've been using it in [rascal](https://github.com/guidesmiths/rascal) for managing RabbitMQ channel pool and it's proved very helpful. We recently had a [bug](https://github.com/guidesmiths/rascal/issues/158) reported which is partially caused because under certain error conditions closing a channel never yields. We do this via the factory destroy override and consequently its promise never resolves. I've fixed this using a timeout, but was wondering what you think about adding a configuration option `destroyTimeoutMillis` which would work in a similar way to `acquireTimeoutMillis`? We would be happy to work on this feature, but conscious that you may not have the time to review, merge and release. Let me know.

Kind regards,

Steve

**Comment by Kikobeats** [comment]
Hey, thanks for reporting. I will happy to accept a PR for this 🙂

What could be a good `destroyTimeoutMillis` default value? I guess you want to be sure resources are gracefully cleaned after a while, but not sure what should be the value there for cover most of the common situations

**Comment by cressie176** [comment]
Hi @Kikobeats,

Thanks for the prompt reply. How about defaulting to no limit to maintain backwards compatibility and to keep it consistent with `acquireTimeoutMillis`?

**Comment by Kikobeats** [comment]
I think it's a good start, yes!

**Comment by cressie176** [comment]
Added via https://github.com/coopernurse/node-pool/pull/289. Thank you
