### ISSUE TITLE
Is there any hooks for .on('error') to remove a driver from the pool?

### ISSUE THREAD

**Issue by mcavage** [coopernurse/node-pool#31]
Hi,

Great module - I didn't see it from briefly scanning your code: it's pretty common that with various drivers (especially stateful/long-lived ones), I'd want to have the pool auto-purge a client that emits an error event, so it can recreate another one to replace it. Is there a way to do that?

Thanks!
~Mark

**Comment by sandfox** [comment]
Going to close due to age reasons. Feel free to re-open if this issue is still relevant anyone.
