### ISSUE TITLE
Events instead of log function

### ISSUE THREAD

**Issue by gagle** [coopernurse/node-pool#55]
Hi,

I'd like to log my own custom errors. Also, I don't want to log every second the message "availableObjects.length=x". Can you inherite the pool from EventEmitter and just emit events so we can catch them and do whatever we want? It's a very easy modification. Just replace this line when you export the module:

``` javascript
var me = {},
```

By this:

``` javascript
var Pool = function (){
  events.EventEmitter.call (this);
};
Pool.prototype = Object.create (events.EventEmitter.prototype);
Pool.prototype.constructor = Pool;
var me = new Pool (),
```

You must add the events module:

``` javascript
var events = require ("events");
```

Then, instead of calling the log function you can throw an event with the data. For example, the createResource function:

``` javascript
me.emit ("create-resource", count, factory.min, factory.max);
```

And to catch it from outside your library:

``` javascript
pool.on ("create-resource", function (count, min, max){
  ...
});
```

**Comment by sandfox** [comment]
Going to close for now until a more concrete proposal or impl comes along.
