### ISSUE TITLE
factory.min should be able to be == factory.max

### ISSUE THREAD

**Issue by thetrancefan** [coopernurse/node-pool#79]
The documentation says
"if this is set > max, the pool will silently set the min to factory.max - 1"

In fact, if you try to set min == max, which should be allowed by the statement above, it is set to max - 1. I worked around this by resetting it in the first call to my create() function. It works fine with min == max, and keeps exactly max objects in the pool as expected.

Thanks for this great library...it really helped me out.

**Comment by sandfox** [comment]
fixed in v3
