### ISSUE TITLE
pool.destroy(obj) is not documented, and requires release() call first

### ISSUE THREAD

**Issue by thetrancefan** [coopernurse/node-pool#80]
Pool.destroy() (that is, NOT the factory.destroy function) is not documented at all in the README.md, but is in fact useful. 

It is especially if the resource being managed can fail and somehow signal that failure. For example, if the resource is a child_process. that child might die, and we then want to remove it from the pool.

This works, but only if pool.release(obj) is called BEFORE calling pool.destroy(). That should also be documented. The comments for pool.destroy say:

"This should be called within an acquire() block as an alternative to release()."

And this statement is just wrong. If release() is not called, the object will not be in availableObjects to be removed by the filter() call in pool.destroy.

Keep up the great work. This is a super useful library.

**Comment by sandfox** [comment]
fixed in v3
