### ISSUE TITLE
how to set timeout for resource acquiring, NOT resource creating?

### ISSUE THREAD

**Issue by tomwang1013** [coopernurse/node-pool#85]
When all the resource are used, is there some way to set a timeout for acquire? I red the source code and found that is there is no resource available and the max limit is reached, the callback of acquire is never called.

**Comment by LightCity** [comment]
I have encountered this problem. it look like a deadlock .

**Comment by kevinburkeshyp** [comment]
maybe a super-simple version could just error immediately if the pool is full? a `block` argument which defaults to true if the pool is full..

**Comment by sandfox** [comment]
@kevinburkeshyp 

I annoyingly haven't had any time to work on this yet. I'd like to have a _proper_ solution for the next major version of this library, but in the meantime haven't come up with any decent "hack around" that would ok drop in the current v2 of the library.  I'd love to have something current v2 users could use that isn't going to be a pain to move from when v3 is released

in terms of possiblr work arounds....

The current version of the pool does return a boolean from the `pool.acquire` function indicating whether the pool is currently fully utilized, `false` if the pool is at full "capacity" and cannot create any new clients, `true` if it isn't and should be able to create new clients.

This doesn't solve the problem of your callout knowing about it though....

Another option is to check the pool's availability before making requesting a resource using one/combination of these synchronous pool methods...

```js
  me.getPoolSize
  me.availableObjectsCount 
  me.waitingClientsCount
  me.getMaxPoolSize
```
 
I'm not quite sure how these would all fit in with the ticket you raised on `node-postgres` though? Do you have easy access to `pg`s pool to use any of the above methods before deciding if to trying to grab a connection?

I'm wary of adding another argument to acquire, but it might represent a sensible stop gap for v2, it would probably have to be a generic `opts` style thing.

Anyway, I'm rambling, let me know what you think about any of this. Hopefully something above lets you do a quick fix, but hopefully we can get something into the library to make this less of a pain!

**Comment by kevinburkeshyp** [comment]
Hi James,
Thanks for writing. I probably can get access to the node pool but I'd be a little worried about a race between reading the pool size and attempting to acquire a resource...

I'll keep thinking about a way to do this right...

**Comment by kevinburkeshyp** [comment]
Patch here: #125, and #127

**Comment by DanielYWoo** [comment]
I have exactly the same problem, and I got OOM with a huge wait clients list. Hopefully generic-pool can provide a safe net like maxWaitingClients, when something bad happens in the application the underlying pool can stop accept new requests to avoid OOM.

**Comment by sandfox** [comment]
this should now be fixed or at work-able round in v3
there is both a maxWaitingClients and acquireTimeout option
