### ISSUE TITLE
Expose a way to get access to pooled objects

### ISSUE THREAD

**Issue by bitsofinfo** [coopernurse/node-pool#88]
Not sure the best way to go about this, I am building a utility that leverages node-pool, and I'd like to be able to dump the status of all the objects currently in the pool (without trying to acquire all of them) If I do it via acquisitions, then I have a weird timing issue to ensure that I don't prematurely release one before I've acquired all instances.. etc. 

In order to do this I need access to the list of instances currently managed by the pool. Both idle and in-use if possible.

May be related to #87

see the hacky thing I am doing here in the "getStatus()" method https://github.com/bitsofinfo/stateful-process-command-proxy/commit/216a8dc582f2188700c96a623bafd79beb85a8b9  to get an idea of what I need to do

**Comment by coopernurse** [comment]
Are you interested in the available objects in the pool?  Or do you need all objects including ones that have been acquired?

**Comment by bitsofinfo** [comment]
Both preferably, but when I read the code I don't see instances that are "checked out" being tracked anywhere.

**Comment by coopernurse** [comment]
Yeah it looks like only available objects are readily available.

The factory interface could almost be used for this.  It gets called on each acquire (if validate is true) and destroy.  But currently it's not called on release.

So one approach would be to optionally let factories implement release() which would effectively turn them into observers.  You could implement a factory that just traces acquire/release/destroy operations.

Would that work?

**Comment by bitsofinfo** [comment]
Actually you just answered my question. Given I already have hooks for destroy & acquire/create I can maintain my own list of all the objects currently out there. Correct me if I'm wrong

**Comment by coopernurse** [comment]
I think the big gap is there's no callback to the factory on release.  So you wouldn't have a good way to know when an object was returned back to the pool.

So currently:

acquire: calls factory.create (new obj) or factory.validate (re-using obj)
destroy: calls factory.destroy
release: missing..  but probably not hard to add.  call factory.release with obj (if factory.release func exists)

**Comment by bitsofinfo** [comment]
Correct, however for my purposes, I'm good without that. I don't particularly care about the state in regards to idle/acquired.

However I strongly agree that it would be good to add. In addition to the pool tracking all the instances itself somewhere (including those checked out).

**Comment by bitsofinfo** [comment]
Hmm, another reason for tracking this internally would be to introduce a function to auto-destroy checked out instances who are beyond a "max checkout time"... Thoughts?

**Comment by coopernurse** [comment]
I agree that enforcing a max checkout time is a useful feature.  Probably should make a separate issue for that.

If you're interested in making a PR for the "release" tracking, please do.  If not I'll keep this ticket open and perhaps another interested person can jump in.

**Comment by bitsofinfo** [comment]
sounds good

**Comment by sandfox** [comment]
I'm going to close this issue as some of the stuff raised has been solved/implemented. If anyone wants to raise any of outstanding requests here as seperate issues that would be cool
