### ISSUE TITLE
Shutting down the whole pool

### ISSUE THREAD

**Issue by akayami** [coopernurse/node-pool#90]
Hi, 

Is there a way to completely shut down the whole pool ? I'm looking for something along the lines of:
```javascript

var poolModule = require('generic-pool');

var pool = poolModule.Pool({
	name: 'vertica',
	create: function(callback) {		
		callback(null, {test: 'test'});
	},
	destroy: function(client) {
		console.log('destroying');
	},	
	max: 10,
	min: 2, 
	idleTimeoutMillis: 10000,
	log: false
});

process.on('SIGINT', function() {
	pool.shutdown(function(err) {
		process.exit();
	});
});
```

I've not seen anything that clearly indicates how one would go about shutting down the pool. 

Thanks.

**Comment by sandfox** [comment]
Does these help? 
https://github.com/coopernurse/node-pool#step-3---drain-pool-during-shutdown-optional
https://github.com/coopernurse/node-pool#draining

The best way to do this does depend slightly on your circumstances and use, and if you can afford to trash pooled resources while they are being loaned.

**Comment by sandfox** [comment]
Going to close this, feel free to re-open if the above solution doesn't help you and you need something else.
