### ISSUE TITLE
releasing verticadb client throws error 

### ISSUE THREAD

**Issue by Abhi11981198** [coopernurse/node-pool#97]
i am using generic-pool for vertica connection. when i release the client,  i.e. pool.release(client) 
it trows error, 

     client.end();
               ^
    TypeError: undefined is not a function
    at Object.poolModule.Pool.destroy (c:\Users\Abhi\nodeServer\hello.js:32:16)
    at Object.me.destroy (c:\Users\Abhi\nodeServer\node_modules\generic-pool\lib\generic-    pool.js:152:13)
    at removeIdle (c:\Users\Abhi\nodeServer\node_modules\generic-pool\lib\generic-pool.js:181:10)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by sandfox** [comment]
without seeing the code inside `hello.js` I can't really do much to help as I can't reproduce the problem.

**Comment by Abhi11981198** [comment]
hello.js 

    
var express = require('express');
var vertica = require('vertica');
var poolModule = require('generic-pool');

var app = express();


var pool = poolModule.Pool({
    name: "poolTest",
    create: function (callback) {
        return vertica.connect({
            host: 'myhost',
            user: 'username',
            password: 'pass',
            database: 'mydb'
        }, function (err, conn) {
            return callback(err, conn);
        });
    },
    destroy: function (client) {
        //console.log(client)
        client.end();
    },
    max: 10,
    // optional. if you set this, make sure to drain() (see step 3)
    //min      : 1,
    // specifies how long a resource can stay idle in pool before being removed
    idleTimeoutMillis: 30000,
    // if true, logs via console.log - can also be a function
    log: false
});

app.get('/', function (req, res) {

    pool.acquire(function (err, client) {
        if (err) {
            // handle error - this is generally the err from your
            // factory.create function
            console.log(err);
        }
        else {
            client.query("select count(*) from user_data ;", function (err, resultSet) {
                // return object back to pool
                console.log(err);
                pool.release(client);
                res.send("working");
            });
        }
    });
    res.send(req.query.abc);

});
        
    
            

var server = app.listen(3000, function () {
    var host = server.address().address;
    var port = server.address().port;

    console.log('Example app listening at http://%s:%s', host, port);
});

this is my hello.js file.

**Comment by Abhi11981198** [comment]
instead of using client.end(), i used client.disconnect(). now, issue is resolved.
