### ISSUE TITLE
feature request: validate hook to support async

### ISSUE THREAD

**Issue by jasonkarns** [coopernurse/node-pool#98]
The validate feature is a great idea in theory, but rather useless when the mechanism to determine validity is async. Any chance of the validate hook accepting a callback?

**Comment by sandfox** [comment]
Sorry it's taken a while to see this, somehow missed the notifications. Seems like a sensible suggestion, I'll have a look and see how easy/hard/messy it will be to add this!

**Comment by einfallstoll** [comment]
+1 the `validate` function is useless for me at the moment.

**Comment by felipou** [comment]
I almost did this a while ago, but it seems to me that this would require a major rewrite of the `dispense` function (using the `async` lib or something similar). At the time I thought it wasn't worth the effort, but it's starting to get more serious for me. Maybe I'll create a pull request soon.

**Comment by felipou** [comment]
Turns out it was fairly easy to do: https://github.com/coopernurse/node-pool/pull/105

**Comment by sandfox** [comment]
fixed in v2.3.0 by #105 - thanks @felipou for this
