### ISSUE TITLE
How is resource exhaustion handled?

### ISSUE THREAD

**Issue by oliversalzburg** [coopernurse/node-pool#99]
I'm currently debugging an issue with node-postgres, which uses this library.

When I'm issuing large amounts of queries, resulting in large amounts of clients being created in the pool, I end up in a situation where requests are never fulfilled.

I tracked this down into generic-pool, which will end up with objects in `waitingClients` (we're setting a max for the pool size), but will never process them.

So, in node-postgres, I noticed a discrepancy between calls to `acquire` and the callback, which is passed to `acquire`, being called. Meaning a callback was queued, but never processed.

Looking at `acquire`, I can see that it basically queues my callback and then invokes `dispense`.

Now, in `dispense`, we check `waitingCount` to see if there is anything queued; something *is* queued. We now check `availableObjects.length`, which is `0`, because all resources are busy. We proceed to check `count < factory.max`, which is false, because the pool size limit has been reached.

We now have 1 queued resource that will never be processed.

I don't see how this is resolved in theory and from what I'm observing in our application, I also don't see how it is resolved in practice.

**Comment by coopernurse** [comment]
`dispense` will be called again when `release` is called, and one of the waitingClients elements will be notified.  If you're seeing deadlock due to starvation, check to make sure you don't have a path where a resource is acquired and then never released.

**Comment by oliversalzburg** [comment]
Thanks for the hint. You're probably right, I'll look into this more in the morning.

**Comment by oliversalzburg** [comment]
The issues I was observing were probably not a problem with node-pool. Thanks :)
